name: PE2

env:
  KERNEL_SOURCE: 'https://github.com/PixelExperience-Devices/kernel_xiaomi_cepheus'
  KERNEL_SOURCE_BRANCH: 'twelve'
  KERNEL_DEFCONFIG: 'cepheus-stock_defconfig'
  KERNEL_NAME: 'PixelExperience'

on:
#   schedule:
#     - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
    - name: Start
      run: |
        ./build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN_GITHUB }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Flashable zip"
        files: |
         


uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            /home/runner/work/kernel-msm/out/arch/arm64/boot/*.zip