name: Build kernel

on: 
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-20.04


    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start
      run: |
        ./build

    - name: releases
uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN_GITHUB }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
            /home/runner/work/kernel-msm/out/arch/arm64/boot/*.zip
